# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_company_myfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='name',
        ),
    ]
