# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_remove_company_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Company',
            new_name='Profile',
        ),
    ]
